---
title: "Climate Perceptions in Toronto"
author: "Lorena Almaraz De La Garza"
date: "April 19th, 2021"
keywords: "X, Y, Z"
output:
  bookdown::pdf_document2: default
subtitle: "with data from Open Data Toronto"
toc: FALSE
thanks: 'Code and data are available in this GitHub repository: [lalmaraz/toronto_climate_perceptions](https://github.com/lalmaraz/toronto_climate_perceptions).'
bibliography: references.bib
abstract: "The abstract text occupies this beautiful space right here. \\par
 \\textbf{Keywords:} search, stackoverflow, find, workaround" 
 
---

```{r libs, include = FALSE, echo=FALSE, message=FALSE, warning=FALSE}
# Load libraries
library(bookdown)
library(ggmap)
library(gt)
library(here)
library(httr)
library(janitor)
library(kableExtra)
library(knitr)
library(opendatatoronto)
library(readxl)
library(rio)
library(tidyverse)
```

# Introduction
[@R]

# Data

## Methodology
## Results

# Discussion

## Findings
## Implications
## Limitations
## Future Work 

```{r echo=FALSE, message=FALSE, warning=TRUE}

```

\newpage
# Appendix 1 {#appendix1}

\newpage
# References
